name: Check all lists
on: 
  push:
    paths:
    - "lists/*"
  pull_request:
    paths:
    - "lists/*"
jobs:
  lint_lists:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install hatch
      run: pip install hatch

    - name: Run lint lists against all lists
      run: hatch run lint-lists lists/
